# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JARVISUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -30, 1181, 951))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 220, 581, 461))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, -70, 361, 261))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 120, 191, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\loading_1.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 181, 151))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\B.G_Template_1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 181, 151))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Code_Template.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(810, 40, 271, 201))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Earth.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 620, 441, 241))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Hero_Template.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(640, 620, 481, 261))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\AIProject\GUI\GUI_FOLDER\Health_Template.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 410, 111, 71))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 90 9pt \"Berlin Sans FB Demi\";\n"
"font: 12pt \"Lucida Bright\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 510, 111, 71))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("font: 90 9pt \"Berlin Sans FB Demi\";\n"
"font: 12pt \"Lucida Bright\";\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(790, 330, 291, 171))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Jarvis_Gui (1).gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "END"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
